### ISSUE TITLE
TODO's

### ISSUE THREAD

**Issue by Cmdv** [Cmdv/purescript-calculator#1]
# Features

- [ ]  - Add a Halogen UI
- [ ]  - Create more comments
- [ ]  - Make some tests
